# Custom Language File for Launcher Customizer

[ejs.app]
title = "Café Showdown! : Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/aegislunarian/CafeLauncher"
mediaXURL = "#"
mediaInstagramURL = "https://www.instagram.com/aegislunarian"
mediaYouTubeURL = "https://www.youtube.com/@LunarianMC"
mediaDiscordURL = "https://discord.gg/PKfSweUgP7"

[ejs.settings]
sourceGithubLink = "https://github.com/aegislunarian/CafeLauncher"
supportLink = "https://github.com/aegislunarian/CafeLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR THE AWAKENING"
welcomeDescription = "Ma mission est, par ce modpack, de vous divertir et faire vivre des moments marquants.  Après nombre d'efforts, ce serveur voit le jour, plus professionnalisé qu'aucun de mes anciens projets."
welcomeDescCTA = "Vous êtes à quelques clics d'une aventure inoubliable."
