[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOUVELLES"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Chargement des nouvelles.."
newsErrorFailedSpan = "Échec du chargement des nouvelles"
newsErrorRetryButton = "Veuillez réessayer"
newsErrorNoneSpan = "Aucune nouvelle"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION : MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "E-MAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se rappeler de moi ?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Vos accès sont transmis directement à Mojang AB et ne sont pas conservés."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié avec Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Séléctionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Séléctionner un compte"
accountSelectConfirm = "Séléctionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter des nouveaux comptes ou modifier ceux existants.."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options relatives au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur dès le lancement."
launchDetachedTitle = "Lancer le jeu indépendamment du launcher"
launchDetachedDesc = "Si le jeu n'est pas lancé de façon indépendante, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changé"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods suppléants"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour rafraishir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Enable or disable shaders. Please note, shaders will only run smoothly on powerful setups. You may add custom packs here."
selectShaderpack = "Séléctionner des shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Configurer Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM Maximale"
minRAM = "RAM Minimale"
memoryDesc = "Je recommande 3 gigas de ram. À noter que mettre le même minimum et maximum peut réduire le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Séléctionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "The Java executable is validated before game launch."
javaPathDesc = "The path should end with <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options executées par la JVM lors de l'exécution. N'incluez ni <em>-Xms</em> ni <em>-Xmx</em>."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Activés les pré-version."
allowPrereleaseDesc = "Les pré-versions inclues des nouveautés à l'avance (aucun engagement).<br>Ce sera toujours actif si vous utilisez la pré-version."
dataDirectoryTitle = "Dossier des donnés"
selectDataDirectory = "Séléctionner le dossier des donnés"
chooseFolder = "Choisir le dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java seront sauvegardés dans le dossier des donnés.<br>Les captures d'écrans et monde solo sont stockés pour chaque serveur indépendemment."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et notes de mises à jour pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de mise à jour"
changelog = "Journal de mise à jour"
noReleaseNotes = "Pas de notes de mise à jour"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et critiquer les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Notes de mises à jour de version"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du Client.."
state = "Serveur: Café Showdown"

[js.index]
microsoftLoginTitle = "Connexion via Microsoft"
microsoftLogoutTitle = "Déconnexion de Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "RÉESSAYER"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue durant la connexion"
desc = "Une erreur inconnue s'est produite. Référez vous à la console (CTRL + Shift + i) pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur durant le lancement"
failureText = "Référez vous à la console (CTRL + Shift + i) pour plus de détails."
okay = "Oki"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte séléctionner"

[js.landing.selectedServer]
noSelection = "Aucun serveur séléctionner"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "ÉTEINT"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérifications des informations systèmes.."
noCompatibleJava = "Pas d'installation<br>Java compatible trouvée"
installJavaMessage = "En vu de lancer Minecraft, vous devez avoir une installation 64-bit de Java {major}. Souhaitez-vous une installation de cette copie ?"
installJava = "Installer Java"
installJavaManually = "Installer Java moi-même"
javaDownloadPrepare = "Préaration de l'installation de Java.."
javaDownloadFailureTitle = "Erreur durant le téléchargement de Java"
javaDownloadFailureText = "Référez vous à la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = """Une installation valide 64-bits de Java {major} est requise pour le lancement.<br><br>Pour l'installer manuellement, référez vous à <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">ce lien</a>."""
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Annuler"

[js.landing.downloadJava]
findJdkFailure = "Distribution OpenJDK non trouvée."
javaDownloadCorruptedError = "Le JDK téléchargé a un mauvais hachage, le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Référez vous à la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur durant le lancement"
seeConsoleForDetails = "Référez vous à la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur durant la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur durant le téléchargement des fichiers"
preparingToLaunch = "Déclaration du lancement.."
launchingGame = "Lancement initié.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, ne s'est pas téléchargé correctement. En conséquence, le jeu ne peut pas être lancé.<br><br>Un moyen de régler le problème est la désactivation de votre Anti-Virus.<br><br>Si vous le pouvez, signaler le bug à <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">HeliosLauncher</a> tout en signalant votre antivirus. L'auteur vous contacteras."
doneEnjoyServer = "Terminé. Profitez du serveur !"
checkConsoleForDetails = "Référez vous à la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérifications des nouvelles"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "En jeu !"
joined = "En jeu !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutable"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose ne va pas"
errorMessage = "La connexion via Microsoft à échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose ne va pas"
errorMessage = "Déconnexion Microsoft échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Séléctionner le compte"
selectedButton = "Compte séléctionner &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C'est votre dernier compte"
lastAccountWarningMessage = "Pour pouvoir utiliser le launcher, un compte est exigé. Vous devrez donc vous reconnecté.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Séléctionner le compte"
selectedAccount = "Compte séléctionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de suppression<br>du mod suppléant {fullName}"
deleteFailedMessage = "Assurez vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de l'activation<br>d'un ou plus Mods suppléants."
okButton = "Oki"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Séléctionné: Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requière Java {major} 64-bit."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version Stable"
releaseNotesFailed = "Échec de chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = """Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermer le launcher et lancer le dmg pour mettre à jour.</span>"""
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Connexion à Microsoft échoué"
errorMessage = "Nous sommes dans l'incapacité de vous connecter à votre compte Microsoft. Veuillez réessayer plus tard."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale: Impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec mes serveurs pour télécharger l'index de distribution. Aucune copie locale n'est disponible. <br><br>L'index de distribution est un fichier essentiel pour récupérer les informations du serveur. Le launcher ne démarrera pas sans. Assurez vous d'être connceté à internet et réessayez."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actulation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Séléctionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mise à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Rechercher des mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur durant la connexion:<br>Profile non réglé"
noProfileDesc = """Votre compte Microsoft n’a pas encore de profil Minecraft configuré. Si vous avez récemment acheté le jeu ou l’avez obtenu via le Xbox Game Pass, vous devez configurer votre profil sur <a href="https://www.minecraft.net/fr-fr/msaprofile">Minecraft.net</a>.<br><br>Si vous n’avez pas encore acheté le jeu, vous pouvez également le faire sur <a href="https://www.minecraft.net/\">Minecraft.net</a>."""
noXboxAccountTitle = "Erreur durant le chargement:<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'a pas de compte Xbox associé."
xblBannedTitle = "Erreur durant la connexion:<br>Xbox Live non disponible"
xblBannedDesc = "Votre compte Microsoft vient d'un pays où Xbox Live n'est pas disponible ou banni."
under18Title = "Erreur durant la connexion:<br>Autorisation parentale requise"
under18Desc = "Les comptes des utilisateurs de moins de 18 ans doivent être ajoutés à une Famille par un adulte."
unknownTitle = "Erreur inconnue durant la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Référez vous à la console (CTRL + Shift + i) pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne:<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne:<br>Non trouvée"
notFoundDesc = "Le point de terminaison d’authentification est introuvable. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur durant la connexion :<br>Compte migré"
accountMigratedDesc = "Vous essayez de vous connecter avec un compte migré. Essayez d'utiliser l'e-mail comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur durant la connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe que vous avez entré est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur durant la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion ont eu lieu avec ce compte. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur durant la connexion :<br>Token invalide"
invalidTokenDesc = "Le token d'accès fournit est invalide."
tokenHasProfileTitle = "Erreur durant la connexion :<br>Le Token a un profile"
tokenHasProfileDesc = "Le token d'accès fournit à déjà un profil associé. Séléctionner un profil n'est pas possible."
credentialsMissingTitle = "Erreur durant la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur ou le mot de passe n'a pas été indiqué ou le mot de passe fait moins de 3 caractères."
invalidSaltVersionTitle = "Erreur durant la connexion :<br>Version de Salt invalide"
invalidSaltVersionDesc = ">Version de salt invalide."
unsupportedMediaTypeTitle = "Erreur interne:<br>Type de Média non supporté"
unsupportedMediaTypeDesc = "Type de Média non supporté. Veuillez me le rapporter (je suis abruti)."
accountGoneTitle = "Erreur durant la connexion :<br>Compte migré"
accountGoneDesc = "Vous avez migré votre compte. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur durant la connexion :<br>Injoignable"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Assurez vous qu'ils fonctionnent et que vous êtes connectés à internet."
gameNotPurchasedTitle = "Erreur durant la connexion :<br>Jeu non possédé"
gameNotPurchasedDesc = "Vous essayez de vous connecté avec un compte qui n'a pas une copie acheté de Minecraft. Vous pouvez en acheté une sur <a href=\"https://minecraft.net/\">https://minecraft.net/\</a>"
unknownErrorTitle = "Erreur inconnue durant la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Référez vous à la console (CTRL + Shift + i) pour plus de détails."
